name: vm-identificator-erros

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *' #Todos os dias as 11:00 - MANHÃ

jobs:
  build:
    runs-on: windows-latest     
    strategy:
      matrix:
        scripts:
          - identificator_complete.py

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Setup Pythom com cache (pip)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency: requirements.txt
          
      - name: Instalação Python + Pip com Cache
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Assegura que o diretório de saída exista
      - name: Criar Diretório de Saída
        run: mkdir -p ${{ env.OUTPUT_DIR }} 

      - name: Executar ${{ matrix.scripts }} 
        run: python ${{ matrix.scripts }} 

      # NOVO PASSO: Criar o Artefato (pasta com as planilhas)
      - name: Upload de Artefato de Resultados
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }} # Usa o nome definido acima: ocr-vm-results
          path: ${{ env.OUTPUT_DIR }} # Pasta que contém as planilhas/arquivos gerados
          retention-days: 7
          if-no-files-found: error # Se o script não gerar a pasta, o job falha
        
      # 1. Baixa o Artefato Gerado no Job Anterior
      - name: Baixar Artefato Gerado
        uses: dawidd6/action-download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME_TO_DOWNLOAD }}
          run_id: ${{ env.RUN_ID_TO_DOWNLOAD }}
          path: ${{ env.ARTIFACT_FOLDER }}
