name: vm-identificator-erros

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'  

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    env:
      OUTPUT_DIR: ${{ github.workspace }}/Encartes
      HTTP_UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/5.0 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

    steps:
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
           python-cache: cache@dependecy
           pip:
            python -m pip install -upgrade pip
      
       - name: Set Directory
         uses: actions/chechout@v4
         with:
          working-directory: "./workflow-github-action"
          if-directory-not-found: "error"
              