name: vm-identificator-erros

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    # Runs at 10:00 UTC every day
    - cron: '0 10 * * *'  

jobs:
  build:
    runs-on: windows-latest
    
    env:
      # This secret MUST be set in your repository: 
      # Settings > Secrets and variables > Actions > New repository secret
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      
      # These environment variables are available to your scripts
      OUTPUT_DIR: ${{ github.workspace }}/Encartes
      HTTP_UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/5.0 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
      
    strategy:
      matrix:
        scripts:
         - spreadsheet.py
         - trainingmodel_ai.py

    steps:
      # Step 1: Check out your repository's code
      - name: Check out repository
        uses: actions/checkout@v4 # Corrected typo 'chechout'

      # Step 2: Set up a Python version
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Caches dependencies to speed up future runs
          
      # Step 3: Install your project's dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # These are the libraries imported in your two .py files
          pip install pandas numpy openpyxl google-generativeai python-dotenv
        shell: pwsh # Use PowerShell on the Windows runner

      # Step 4: Run the Python script from the matrix
      - name: Run ${{ matrix.scripts }}
        run: python ${{ matrix.scripts }}
        shell: pwsh